// @OUTPUT@

const theOutput = [
  {
    stepNumber: 0,
    stepName: "personal details",
    type: "title",
    binary: true,
    before: "",
    after: "",
    value: "פרטים אישיים",
    newSection: true,
    page: null,
    source: null,
  },
  {
    stepNumber: 1,
    stepName: "gender",
    type: "content",
    binary: true,
    before: "",
    after: "",
    value: null,
    newSection: false,
    page: null,
    source: null,
  },
  {
    stepNumber: 2,
    stepName: "age",
    type: "content",
    binary: false,
    before: "",
    after: ",",
    value: null,
    newSection: false,
    page: null,
    source: null,
  },
  {
    stepNumber: 3,
    stepName: "religion",
    type: "content",
    binary: false,
    before: "",
    after: ",",
    value: null,
    newSection: false,
    page: null,
    source: null,
  },
];
