const theOutput = [
  {
    stepNumber: 0,
    stepName: "personal details",
    type: "title",
    openTag: "<span>",
    closeTag: "</span>",
    binary: true,
    before: null,
    after: null,
    value: "פרטים אישיים",
    newSection: true,
    link: null,
    source: null,
  },
  {
    stepNumber: 1,
    stepName: "gender",
    type: "content",
    openTag: "<span>",
    closeTag: "</span>",
    binary: true,
    before: null,
    after: null,
    value: "בן",
    newSection: false,
    link: null,
    source: null,
  },
  {
    stepNumber: 2,
    stepName: "age",
    type: "content",
    openTag: "<span>",
    closeTag: "</span>",
    binary: false,
    before: null,
    after: ",",
    value: "33",
    newSection: false,
    link: null,
    source: null,
  },
  {
    stepNumber: 2,
    stepName: "age",
    type: "content",
    openTag: "<span>",
    closeTag: "</span>",
    binary: false,
    before: null,
    after: ",",
    value: "נשוי",
    newSection: false,
    link: null,
    source: null,
  },
  {
    stepNumber: 2,
    stepName: "age",
    type: "content",
    openTag: "<span>",
    closeTag: "</span>",
    binary: false,
    before: null,
    after: ",",
    value: "בלה",
    newSection: false,
    link: null,
    source: null,
  },
  {
    stepNumber: 1,
    stepName: "gender",
    type: "content",
    openTag: "<span>",
    closeTag: "</span>",
    binary: true,
    before: null,
    after: " ",
    value: null,
    newSection: false,
    link: null,
    source: null,
  },
  {
    stepNumber: 2,
    stepName: "age",
    type: "content",
    openTag: "<span>",
    closeTag: "</span>",
    binary: false,
    before: null,
    after: ",",
    value: "סוף",
    newSection: false,
    link: null,
    source: null,
  },
  {
    stepNumber: 2,
    stepName: "age",
    type: "content",
    openTag: "<span>",
    closeTag: "</span>",
    binary: false,
    before: null,
    after: ",",
    value: "123123123123",
    newSection: true,
    link: null,
    source: null,
  },
];

// OTHERS

let maleNumbers = [
  undefined,
  undefined,
  "שני",
  "שלושה",
  "ארבעה",
  "חמישה",
  "שישה",
  "שבעה",
  "שמונה",
  "תשעה",
  "עשרה",
];

let componentBackground = [
  "#ffadad",
  "#ffd6a5",
  "#fdffb6",
  "#caffbf",
  "#9bf6ff",
  "#a0c4ff",
  "#bdb2ff",
  "#ffc6ff",
];

let sectionBackground = ["#540d6e", "#ee4266", "#ffd23f", "#3bceac", "#0ead69"];
